site_name: Talk to Defuse

theme:
  name: material

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Usage: usage.md
  - Modules:
      - Overview: modules/modules-list.md
      - Switch Module: modules/switch.md
      - Simon Says: modules/simon.md
      - Labyrinth: modules/labyrinth.md
      - Hand Skill Module: modules/hand-skill.md
      - Morse Code Module: modules/morse-code.md
      - Cables Module: modules/cables.md
  - Essential Components: essentialcomponents.md
  - 3D Models: 3dmodels.md
  - Troubleshooting: troubleshooting.md
  - Contributing: contributing.md
  - FAQ: faq.md
  - About: about.md
  - License & Sales: lisance-&-sales.md
  - Changelog: changelog.md
  - Sales:
      - Overview: sales/overview.md
      - Outer Case Sales: sales/outer-case.md
      - Circuit Boards: sales/pcbs.md
      - Full Modules: sales/full-modules.md
      - Kit Sales: sales/kits.md
      - Purchase Terms: sales/buying-conditions.md
  - Support: support.md
docs_dir: Talk-To-Defuse/docs

